services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_20260719:/var/lib/postgresql/data
      - ../02_database/tables.sql:/docker-entrypoint-initdb.d/tables.sql

volumes:
  postgres_data_20260719: