services:
  database:
    image: postgres:17
    container_name: testdb
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=hurwan
      - POSTGRES_PASSWORD=1234

    ports:
      - "5432:5432"

    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d

volumes:
  postgres-db: